### PR TITLE
Optimizations and a fix.

### PR DESCRIPTION
**Pull request by Darkhax**
This PR makes a few optimizations to the static json and image files in your mod. I wasn't able to build the mod using your provided gradle so I don't have the exact size reductions but it's a few KB. The optimizations include

- Removing metadata from some images. This isn't actually used and is just junk data here.
- Added lossless compression to images. This doesn't affect the quality or color. They are also compatible with the PNG spec. 
- Added auto json minification at build time. This will remove superfluous new line and white space characters from json at build time. The original source copies are not modified, only the jar copies. 

I also edited the manifest data to include your mod name as the title and your name as the vendor. While this info isn't really used it's better than supplying incorrect information.

### CODE REVIEW

**Comment by VulpTheHorseDog** [comment]
Oh nice, thanks so much! I'm assuming it's a set and forget fix in regards to everything but the images? I'll have to look into the compression for my art program.

**Comment by Darkhax** [comment]
Yeah, images will be fine until you next edit them.

**Comment by VulpTheHorseDog** [comment]
Thank you! It's really appreciated.

**Comment by noobanidus** [comment]
Were you using optipng Darkhax?

**Comment by Darkhax** [comment]
@noobanidus I used ZOPFLI via the PINGO suite. They have a GUI called Pinga as well.

**Pull request merged**
